---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - ./heimdall:/config
    ports:
      - 8080:80
    restart: unless-stopped
