---
version: "2.1"
services:
  wallabag:
    image: ugeek/wallabag:arm
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.0.100
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    volumes:
      - ./wallabag/data:/var/www/wallabag/data
      - ./wallabag/images:/var/www/wallabag/web/assets/images
    ports:
      - 80:80
    restart: unless-stopped
